name: glider_models
description: A library of models, classes, extensions, and more used by Glider.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  hover:
    path: ../hover
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

