name: glider_sensors
description: Glider library for accessing hardware sensors. 
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  battery_plus: ^1.0.2
  camera: ^0.8.1+3
  flutter:
    sdk: flutter
  glider: 
    path: ../glider
  hover: 
    path: ../hover
  image: ^3.0.2
  image_picker: ^0.8.2
  sensors_plus: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true