name: glider_sensors
description: Glider library for accessing hardware sensors. 
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-268.18.beta <3.0.0"

dependencies:
  battery_plus: ^2.0.2
  camera: ^0.9.4+5
  flutter:
    sdk: flutter
  glider: 
    path: ../glider
  hover: 
    path: ../hover
  image: ^3.1.0
  image_picker: ^0.8.4+4
  sensors_plus: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true