name: glider_demo
description: Glider Demo app. 
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  battery_plus: ^1.0.2
  camera: ^0.8.1+3
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  glider: 
    path: ../../glider
  google_fonts: ^2.1.0
  hover:
    path: ../../hover
  http: ^0.13.3
  image: ^3.0.2
  image_picker: ^0.8.2
  intl: ^0.17.0
  provider: ^5.0.0
  sensors_plus: ^1.0.2
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true