name: glider_demo
description: Glider Demo app. 
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-268.18.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  glider: 
    path: ../../glider
  hover:
    path: ../../hover

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true