name: glider
description: A library for developing 3 layer architecture apps with Flutter. 
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-268.18.beta <3.0.0"

dependencies:
  cupertino_icons: ^1.0.4
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  glider_models: 
    path: ../glider_models
  google_fonts: ^3.0.1
  hover: 
    path: ../hover
  http: ^0.13.4
  intl: ^0.17.0
  provider: ^6.0.1
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true