name: glider
description: A library for developing 3 layer architecture apps with Flutter. 
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  glider_models: 
    path: ../glider_models
  google_fonts: ^2.1.0
  hover: 
    path: ../hover
  http: ^0.13.3
  intl: ^0.17.0
  provider: ^5.0.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true